app = "fly-wordpress-sqlite"

[env]
WORDPRESS_CONFIG_EXTRA = "define('DB_FILE', 'db.sqlite'); define('DB_DIR', '/data/db'); define('UPLOADS', '/data/uploads');"
#WORDPRESS_DEBUG = 1

[mounts]
source = "fly_wordpress_sqlite_data"
destination = "/data"

[[services]]
internal_port = 80
protocol = "tcp"

[services.concurrency]
hard_limit = 50
soft_limit = 25

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.ports]]
handlers = ["http"]
port = 80

[[services.tcp_checks]]
grace_period = "1s"
interval = 5000
timeout = 2000
